### ISSUE TITLE
Future of Snowstorm-X

### ISSUE THREAD

**Issue by rrapio** [IHTSDO/snowstorm-x#1]
What is the roadmap for Snowstorm-X regarding the creation of code systems and mappings? Does the roadmap include creation of these entities through FHIR API operations (i.e. POST CodeSystem and ConceptMap)?

**Comment by kaicode** [comment]
Yes, the creation of code systems and concept maps via PUT or POST is on the roadmap for code systems that are not SNOMED CT.
SNOMED CT code systems will continue to be imported via RF2 or planned syndication service because not all of the information can be represented in a FHIR format.

**Comment by kaicode** [comment]
A new beta was released today but this issue has not been addressed yet.

**Comment by rrapio** [comment]
Thank you for the response. Closing the issue, since it is about knowing the roadmap rather than the feature development itself. I am evaluating the server for a project, but this feature is a must-have for our use case. I will keep watching.
