### ISSUE TITLE
Cardinality in ECL-expansion

### ISSUE THREAD

**Issue by Tannjorn** [IHTSDO/snowstorm-x#10]
Is there a way to use cardinality in ECL expansion against a postcoordination repository? In the browser, and "inside" the terminology I can do things like: <<404684003 |Clinical finding|:[2..2]116676008 |Associated morphology|=*

Trying the same returns "Bad request" run against the FHIR-api.

My use-case is a bit complicated. We have tested extensive use of postcoordinations, ending with approximately 32000 postcoordinations. Everything else works fine, except for cardinality. According to (what I belive is wrong modelling) we have multiple anatomical concepts, up to 6. The pattern is one tooth, and 0 to 5 relative locations (surfaces). I would like to be able to filter how many relative locations are in a post-coordination. For instance I would like to find all postcoordinations with two, and only two, surfaces.

The query would look something like this:
fhir_vs=ecl/<<442551007 |Dentin caries|:
363698007 |Finding site|=<<1186775004 |Structure of deciduous second molar tooth|,
[2..2]363698007 |Finding site|=<<245644000 |Single tooth surface|

Being able to do this would enable automated claims from charting, and more advanced analytics.

Or is it just not possible?

// Jørn

**Comment by kaicode** [comment]
Hi Jørn,
Yes, this works. Make sure the ECL is URL encoded to prevent getting a Bad Request error.
In your example replacing `[2..2]` with `%5B2..2%5D` allows the request to work.
There is a manual URL Encoder tool here: https://www.urlencoder.org/

**Comment by Tannjorn** [comment]
Thanks Kai,
I think Postman, which I have used a lot, have some minor snags regarding this. Or I have simply messed it up. But with a bit back and forth I have been able to make it work, and now it does exactly what I wanted it to do.

Closing the question.

// Jørn
