### ISSUE TITLE
HL7 ValueSets not being imported

### ISSUE THREAD

**Issue by rrapio** [IHTSDO/snowstorm-x#2]
After importing the HL7 Terminologies NPM package, only CodeSystems are imported, but none of the many ValueSets contained in the package.

**Comment by kaicode** [comment]
We are actively working on this. Expect a new release before the end of the year.

**Comment by kaicode** [comment]
Beta 8.2.0 was released today. That includes importing ValueSets from FHIR packages. It also includes some other features that are required to expand the ValueSets within the HL7 terminology package.

**Comment by rrapio** [comment]
Great, I will check it out! Thank you
