### ISSUE TITLE
Validation of SNOMED Expression using the FHIR API ($validate-code)

### ISSUE THREAD

**Issue by olaf-rode** [IHTSDO/snowstorm-x#5]
Hi,
currently we are evaluating Snowstorm for internal use and are testing required functionality. We identified an issue/question relating the FHIR $validate-code Operation. Are there any plans to support the validation of SNOMED Expressions using this operation? As stated in the FHIR specs (https://hl7.org/fhir/snomedct.html) it should be possible to provide an expression as code.

Thank you!

**Comment by kaicode** [comment]
Yes, `CodeSystem/$validate-code` will be implemented for expressions. I am currently focused on creating the next Snowstorm X beta which will have postcoordination functionality in the FHIR interface. Current target is the end of Jan.

**Comment by olaf-rode** [comment]
That sounds great. Thanks for the fast reply.
