### ISSUE TITLE
Creating ValueSets using POST (FHIR API) is allowed in read-only-mode (v8.1.1)

### ISSUE THREAD

**Issue by olaf-rode** [IHTSDO/snowstorm-x#6]
Hi,

i just played around with the FHIR API and the provided postman-collection. When trying to create a ValueSet with the POST-Operation in read-only-mode it still worked. There might be an issue with the access control rules. PUT and DELETE Operations seem not to be affected.

--> v8.1.1

Hope this helps ...

**Comment by kaicode** [comment]
Thanks @olaf-rode, I'll review all the permissions of all FHIR operations when in read-only mode.

**Comment by kaicode** [comment]
This is fixed in SnowstormX release 8.3.0.
