### ISSUE TITLE
Newly created code system (with Swagger) is not visible on FHIR

### ISSUE THREAD

**Issue by karoltech** [IHTSDO/snowstorm-x#8]
We create a code system supplement on Swagger, using the guidelines on https://github.com/IHTSDO/snowstorm-x/blob/master/docs/updating-snomed-and-extensions.md, e.g. 
{
  "shortName": "SNOMEDCT-MYCODESYSTEM",
  "branchPath": "MAIN/SNOMEDCT-MYCODESYSTEM",
  "dependantVersion": 20230131
}
where the international version 20230131 is uploaded on the server, and an extension already created with the same guidelines. 

The problem is that the new code system created is not visible using the FHIR API: 
GET /CodeSystem
while this code system is visible through Swagger. 

1) Is there a way to access the newly created code system from Swagger? 

2) Is there a way to specify that the code system is a supplement?

**Comment by kaicode** [comment]
There are two types of CodeSystem.

1. There are Snowstorm CodeSystems, they always use the SNOMED-CT terminology and can be accessed via the Snowstorm Swagger API. These can be created before uploading a release. When importing a release the SNAPSHOT type should be used and the createCodeSystemVersion=true flag. This will create a version under that CodeSystem.

2. There are also the FHIR CodeSystem resource that are accessed using the FHIR API. There is a separate FHIR CodeSystem for each version SNOMED CT. No FHIR CodeSystems will be listed until a version of SNOMED CT is imported.

This is the normal way of dealing with published content. Snowstorm does allow accessing SNOMED CT content that has not yet been versioned, for example if serving a daily build from an authoring platform but I assume this is not relevant to your scenario.

**Comment by karoltech** [comment]
Thank you Kai for the fast and clarifying response.

**Comment by kaicode** [comment]
You are welcome!
